[build]
  command = "npm run build"
  publish = ".netlify/output/client"
  functions = ".netlify/functions"

[functions]
  directory = ".netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 