[build]
  command = "npm run build"
  publish = ".netlify/output"

[dev]
  command = "npm run dev"
  port = 3000

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[functions]
  directory = "functions" 